
#网站的地址
web: 
  host: "127.0.0.1"
  port: 11451
#webui的接口
webui_api: "127.0.0.1:7860"


#启用翻译
#注意！目前只对中文提供翻译
chans: 
  #我这里仅提供百度和有道两种选择("baidu","youdao")
  site: ""
  #对应有道云应用ID 
  api_key: ""
  #对应有道云应用密钥
  secret_key: ""


#是否保存生成图片在本地
#注意，webuiapi生成的图片并不会自动保存
SAVE: true



#------------------------调试的配置(一般用不上)---------------------------
#启用数据库
#这里是预留给我机器人的接口，所以，如果你不会用的话，就不要使用啦！
sql: 
  open: "ON"
  name: "whitecat"



#日志等级
log_level: "DEBUG"

#是否将web_server信息写入日志
#注意！此方法将导致命令行不再显示fastapi的信息
log_save: false